### ISSUE TITLE
`cls.CLASSES` or `classes` should be specified when testing

### ISSUE THREAD

**Issue by JunzheJosephZhu** [XiongweiWu/FoodSeg103-Benchmark-v1#19]
Hi, I'm trying to run the test script but encountered this error:
CUDA_VISIBLE_DEVICES=0  python  -m torch.distributed.launch --nproc_per_node=4  --master_port=${PORT:-4040} tools/test.py  checkpoints/SETR_Naive_ReLeM/SETR_Naive_768x768_80k_base.py   checkpoints/SETR_Naive_ReLeM/iter_80000.pth  --launcher pytorch --eval mIoU

Traceback (most recent call last):
  File "/home/joseph/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/joseph/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmseg/datasets/custom.py", line 117, in __init__
    '`cls.CLASSES` or `classes` should be specified when testing'
AssertionError: `cls.CLASSES` or `classes` should be specified when testing

**Comment by JunzheJosephZhu** [comment]
I think I solved the issue, I didn't realize this was a fork of mmseg, so I followed the instructions in get_started.md and installed the official version of mmseg
